// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmallPayload.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Shared.GeneratedCode {
  public static partial class SmallPayloadService
  {
    static readonly string __ServiceName = "SmallPayloadService";

    static readonly grpc::Marshaller<global::SmallRequest> __Marshaller_SmallRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SmallRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SmallResponse> __Marshaller_SmallResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SmallResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::SmallRequest, global::SmallResponse> __Method_SendSmallPayload = new grpc::Method<global::SmallRequest, global::SmallResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendSmallPayload",
        __Marshaller_SmallRequest,
        __Marshaller_SmallResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SmallPayloadReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SmallPayloadService</summary>
    public abstract partial class SmallPayloadServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::SmallResponse> SendSmallPayload(global::SmallRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SmallPayloadService</summary>
    public partial class SmallPayloadServiceClient : grpc::ClientBase<SmallPayloadServiceClient>
    {
      /// <summary>Creates a new client for SmallPayloadService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SmallPayloadServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SmallPayloadService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SmallPayloadServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SmallPayloadServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SmallPayloadServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::SmallResponse SendSmallPayload(global::SmallRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendSmallPayload(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SmallResponse SendSmallPayload(global::SmallRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendSmallPayload, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SmallResponse> SendSmallPayloadAsync(global::SmallRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SendSmallPayloadAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SmallResponse> SendSmallPayloadAsync(global::SmallRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendSmallPayload, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SmallPayloadServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SmallPayloadServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SmallPayloadServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SendSmallPayload, serviceImpl.SendSmallPayload).Build();
    }

  }
}
#endregion
